### ISSUE TITLE
Doesn't work... says  Missing JSONS input

### ISSUE THREAD

**Issue by DmitriyAlergant-T1A-Rogers** [nhalstead/validate-json-action#9]
I've started with the original action ([OrRosenblatt](https://github.com/OrRosenblatt)) and it works, though missing glob support.

The configuration is very simple (no globs, yet) - and it works.

```
name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: schema.json
          INPUT_JSONS: /jsons/test.json
```

I'm replacing "uses" with **nhalstead/validate-json-action@0.1.3** with no other changes, and it stops working - fails with "Missing JSONS input" error. What am I doing wrong?

**Comment by nhalstead** [comment]
Hi @DmitriyAlergant-T1A-Rogers thank you for your paitence, I didn't get a notification of this issue.

You can see the example in the [Readme.md](https://github.com/nhalstead/validate-json-action#example-workflow).

**Comment by SchoolGuy** [comment]
@DmitriyAlergant-T1A-Rogers What you probably want is the following:

```yml
name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        with:
          schema: schema.json
          jsons: /jsons/test.json
```
